/* 
* Generated by
* 
*      _____ _          __  __      _     _
*     / ____| |        / _|/ _|    | |   | |
*    | (___ | | ____ _| |_| |_ ___ | | __| | ___ _ __
*     \___ \| |/ / _` |  _|  _/ _ \| |/ _` |/ _ \ '__|
*     ____) |   < (_| | | | || (_) | | (_| |  __/ |
*    |_____/|_|\_\__,_|_| |_| \___/|_|\__,_|\___|_|
*
* The code generator that works in many programming languages
*
*			https://www.skaffolder.com
*
*
* You can generate the code from the command-line
*       https://npmjs.com/package/skaffolder-cli
*
*       npm install -g skaffodler-cli
*
*   *   *   *   *   *   *   *   *   *   *   *   *   *   *   *
*
* To remove this comment please upgrade your plan here: 
*      https://app.skaffolder.com/#!/upgrade
*
* Or get up to 70% discount sharing your unique link:
*       https://app.skaffolder.com/#!/register?friend=5ea8cb8382f82d390e77f827
*
* You will get 10% discount for each one of your friends
* 
*/
package com.skaffolder_teste.db.teste_db.service.base;

import java.util.ArrayList;
import java.util.List;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.transaction.annotation.Transactional;
import org.springframework.stereotype.Service;


import com.skaffolder_teste.db.teste_db.entity.Cliente;

import com.skaffolder_teste.db.teste_db.entity.User;

import com.skaffolder_teste.db.teste_db.repositories.ClienteRepository;

@Service
@Transactional
public class ClienteBaseService {

	
	@Autowired
	ClienteRepository clienteRepository;


    // CRUD METHODS
    
    // CRUD - CREATE
    
	public Cliente insert(Cliente cliente) {
		return clienteRepository.save(cliente);
	}
	
	// CRUD - REMOVE
    
	public void delete(Long id) {
		clienteRepository.delete(id);
	}

    
    // CRUD - FIND BY Cliente_User

    public List<Cliente> findByCliente_User(User user) {
		return clienteRepository.findByCliente_User(user);
	}
    
	// CRUD - GET ONE
    	
	public Cliente getOne(Long id) {
		return clienteRepository.findOne(id);
	}

    	
    // CRUD - GET LIST
    	
	public List<Cliente> getAll() {
		List<Cliente> list = new ArrayList<>();
		clienteRepository.findAll().forEach(list::add);
		return list;
	}
	

}
